[EDIT] Bonus to clear names

diff --git a/bonus/chocolatine.yml b/bonus/chocolatine.yml
--- a/bonus/chocolatine.yml
+++ b/bonus/chocolatine.yml
@@ -21,7 +21,7 @@ env:
   AUTHORIZED: "write,malloc,free"
 
 jobs:
-  check_repository:
+  Check Repository to Start Jobs:
     runs-on: ubuntu-latest
     steps:
       - name: checkout@v4
@@ -36,8 +36,74 @@ jobs:
             exit 1
           fi
 
-  check_banned_functions:
-    needs: check_repository
+  Check Any Coding Style Errors:
+    needs: [Check Repository to Start Jobs]
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+
+      - name: Run Coding-Style-Checker
+        run: check.sh $(pwd) $(pwd)
+
+      - name: Check Any Error
+        run: |
+          cat coding-style-reports.log | while read line; do
+            TYPE=$(echo $line | cut -d ':' -f 3 | cut -c 2-)
+            temp=$(echo $line | cut -d ':' -f 1)
+            NAME=$(echo $temp | cut -d '/' -f 2)
+            LINE=$(echo $line | cut -d ':' -f 2)
+            NBR=$(echo $line | cut -d ':' -f 4)
+            ERROR=$(printf "%s coding style error" "$TYPE")
+            echo "::error file=$NAME,line=$LINE,title=$ERROR::$NBR"
+          done
+          if [ -s coding-style-reports.log ]; then
+            exit 1
+          else
+            exit 0
+          fi
+
+  Check Program Compilation:
+    needs: [Check Any Coding Style Errors]
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+      - name: Compilation
+        run: make
+        timeout-minutes: 2
+      - name: Clean
+        run: make clean
+      - name: Check Executables
+        run: |
+          IFS=',' read -ra array <<< "$EXECUTABLES"
+          for arg in "${array[@]}"; do
+            if [ ! -x "$arg" && ! -f "$arg" ]; then
+              printf "::error::%s does not exist or is not executable" "$arg"
+              exit 1
+            fi
+          done
+          exit 0
+
+  Run Unit Tests:
+    needs: [Check Program Compilation]
+    runs-on: ubuntu-latest
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+      - name: Run Unit Tests
+        run: make tests_run
+        timeout-minutes: 2
+
+  Check Banned Functions in Executables:
+    needs: [Run Unit Tests]
+    if: ${{ needs.check_repository.outputs.target == 0 }}
     runs-on: ubuntu-latest
     steps:
       - name: checkout@v4
@@ -71,73 +137,8 @@ jobs:
           done
           exit 0
 
-  check_coding_style:
-    needs: check_banned_functions
-    runs-on: ubuntu-latest
-    container:
-      image: ghcr.io/epitech/coding-style-checker:latest
-    steps:
-      - name: checkout@v4
-        uses: actions/checkout@v4
-
-      - name: Run Coding-Style-Checker
-        run: check.sh $(pwd) $(pwd)
-
-      - name: Check Any Error
-        run: |
-          cat coding-style-reports.log | while read line; do
-            TYPE=$(echo $line | cut -d ':' -f 3 | cut -c 2-)
-            temp=$(echo $line | cut -d ':' -f 1)
-            NAME=$(echo $temp | cut -d '/' -f 2)
-            LINE=$(echo $line | cut -d ':' -f 2)
-            NBR=$(echo $line | cut -d ':' -f 4)
-            ERROR=$(printf "%s coding style error" "$TYPE")
-            echo "::error file=$NAME,line=$LINE,title=$ERROR::$NBR"
-          done
-          if [ -s coding-style-reports.log ]; then
-            exit 1
-          else
-            exit 0
-          fi
-
-  check_program_compilation:
-    needs: check_coding_style
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker:latest
-    steps:
-      - name: checkout@v4
-        uses: actions/checkout@v4
-      - name: Compilation
-        run: make
-        timeout-minutes: 2
-      - name: Clean
-        run: make clean
-      - name: Check Executables
-        run: |
-          IFS=',' read -ra array <<< "$EXECUTABLES"
-          for arg in "${array[@]}"; do
-            if [ ! -x "$arg" && ! -f "$arg" ]; then
-              printf "::error::%s does not exist or is not executable" "$arg"
-              exit 1
-            fi
-          done
-          exit 0
-
-  run_tests:
-    needs: check_program_compilation
-    runs-on: ubuntu-latest
-    container:
-      image: epitechcontent/epitest-docker:latest
-    steps:
-      - name: checkout@v4
-        uses: actions/checkout@v4
-      - name: Run Unit Tests
-        run: make tests_run
-        timeout-minutes: 2
-
-  push_to_mirror:
-    needs: run_tests
+  Push to Target Repository:
+    needs: [Check Banned Functions in Executables]
     if: ${{ github.event_name == 'push' }}
     runs-on: ubuntu-latest
     steps:
