[ADD] Jigglypuff in the bonus/ folder

diff --git a/bonus/chocolatine.yml b/bonus/chocolatine.yml
--- a/bonus/chocolatine.yml
+++ b/bonus/chocolatine.yml
@@ -2,10 +2,11 @@
 ## EPITECH PROJECT, 2023
 ## chocolatine
 ## File description:
-## First use of github workflow
+## Bonus
 ##
 
 name: chocolatine
+
 
 on:
   push:
@@ -15,12 +16,40 @@ on:
     branches-ignore:
       - "ga-ignore-*"
 
+
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-NAN-2-1-chocolatine-matisse.marsac.git"
   EXECUTABLES: "secured"
+  AUTHORIZED: "write,malloc,free"
+
 
 jobs:
+  draw_jigglypuff:
+    name: Secret Job ;)
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+
+      - name: CLICK HERE TO SEE "ART"
+        run: |
+          echo "::notice title=RONDOUDOU::CLICK HERE"
+          echo "
+                    ⢀⣀⣀⡠⠖⢉⣌⢆
+          ⠀⠀⠀⠀⠀⠀⠀⣠⠚⠉⠀⠈⠉⠲⣿⣿⡜⡀
+          ⡔⢉⣙⣓⣒⡲⠮⡇⠀⠀⠀⠀⠀⠀⠘⡿⡇⡇
+          ⡇⠘⣿⣿⣿⠏⠀⠀⠠⣀⡀⠀⠀⠀⠀⡇⠈⠳⡄
+          ⢹⠀⢻⣿⠇⠀⠀⣀⣀⠀⡍⠃⠀⠀⣠⣷⡟⢳⡜⡄
+          ⠈⣆⠀⠋⢀⢔⣵⣿⠋⠹⣿⠒⠒⠚⠁⣿⣿⣾⣷⢸⠤⡄
+          ⠀⡇⠀⠀⢸⢸⣿⣿⣶⣾⡏⡇⠀⠀⢀⡘⣝⠿⡻⢸⡰⠁
+           ⢳⠀⠀⠈⢆⠻⢿⡿⠟⡱⠁⠰⠛⢿⡇⠀⠉⠀⡸⠁
+           ⠈⢆⠀⠀⠀⠉⠒⠒⣉⡀⠀⠀⢇⠀⡇⠀⠀⢠⠃
+            ⠈⠣⡀⠀⠀⠀⠀⠀⢉⡱⠀⠀⠉⠀⢀⡴⠁
+            ⠀⠀⠈⠓⠦⣀⣉⡉⠁⢀⣀⣠⠤⠒⠥⣄
+            ⠀⠀ ⠰⣉⣀⣀⡠⠭⠛⠀⠀⠑⠒⠤⠤⠷"
+
   check_repository:
+    name: Check Repository to Start Jobs
     runs-on: ubuntu-latest
     outputs:
       target: ${{ steps.new_output.outputs.value }}
@@ -41,7 +70,8 @@ jobs:
           exit 0
 
   check_coding_style:
-    needs: [check_repository]
+    name: Check Any Coding Style Errors
+    needs: [check_repository,draw_jigglypuff]
     if: ${{ needs.check_repository.outputs.target == 0 }}
     runs-on: ubuntu-latest
     container:
@@ -71,6 +101,7 @@ jobs:
           fi
 
   check_program_compilation:
+    name: Check Program Compilation
     needs: [check_coding_style]
     runs-on: ubuntu-latest
     container:
@@ -78,11 +109,14 @@ jobs:
     steps:
       - name: checkout@v4
         uses: actions/checkout@v4
+
       - name: Compilation
         run: make
         timeout-minutes: 2
+
       - name: Clean
         run: make clean
+
       - name: Check Executables
         run: |
           IFS=',' read -ra array <<< "$EXECUTABLES"
@@ -95,6 +129,7 @@ jobs:
           exit 0
 
   run_tests:
+    name: Run Unit Tests
     needs: [check_program_compilation]
     runs-on: ubuntu-latest
     container:
@@ -102,12 +137,50 @@ jobs:
     steps:
       - name: checkout@v4
         uses: actions/checkout@v4
+
       - name: Run Unit Tests
         run: make tests_run
         timeout-minutes: 2
 
-  push_to_mirror:
+  check_banned_functions:
+    name: Check Banned Functions in Executables
     needs: [run_tests]
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+
+      - name: run-compilation
+        run: make re
+        timeout-minutes: 2
+
+      - name: check-banned
+        run: |
+          IFS=',' read -ra array <<< "${{ env.EXECUTABLES }}"
+          IFS=',' read -ra auth <<< "${{ env.AUTHORIZED }}"
+          for arg in "${array[@]}"; do
+            commands=$(nm "$arg" | grep " U " | sed 's/^.* U \([^@]*\).*/\1/'| grep -v '__*')
+            temp=()
+            readarray -t temp <<< "$commands"
+            for cmd in "${temp[@]}"; do
+              authorized=false
+              for func in "${auth[@]}"; do
+                if [[ "$cmd" == "$func" ]]; then
+                  authorized=true
+                  break
+                fi
+              done
+              if [[ $authorized == false ]]; then
+                echo "::error title=Unauthorized function used!::$cmd"
+                exit 1
+              fi
+            done
+          done
+          exit 0
+
+  push_to_mirror:
+    name: Push to Target Repository
+    needs: [check_banned_functions]
     if: ${{ github.event_name == 'push' }}
     runs-on: ubuntu-latest
     steps:
@@ -115,6 +188,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
       - name: Repository Mirroring
         uses: pixta-dev/repository-mirroring-action@v1
         with:
