[EDIT] error to notice

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -28,13 +28,6 @@ jobs:
         uses: actions/checkout@v4
       - name: run-coding-style
         run: check.sh $(pwd) $(pwd)
-      - name: continue
-        run: |
-          if [ -s coding-style-reports.log ]; then
-            exit 1
-          else
-            exit 0
-          fi
       - name: check_any_error
         if: ${{ failure() }}
         run: |
@@ -43,8 +36,15 @@ jobs:
             temp=$(echo $line | cut -d ':' -f 1)
             NAME=$(echo $temp | cut -d '/' -f 2)
             LINE=$(echo $line | cut -d ':' -f 2)
-            echo "::error col=1::${TYPE} coding style error: ${NAME}#L${LINE}"
+            echo "::notice col=1::${TYPE} coding style error: ${NAME}#L${LINE}"
           done
+      - name: continue
+        run: |
+          if [ -s coding-style-reports.log ]; then
+            exit 1
+          else
+            exit 0
+          fi
   # check_program_compilation:
   # run_tests:
   # push_to_mirror:
