[RM] banned functions in main.c

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -49,26 +49,26 @@ jobs:
         timeout-minutes: 2
       - name: check-banned
         run: |
-            IFS=',' read -ra array <<< $EXECUTABLES
-            IFS=',' read -ra auth <<< $AUTHORIZED
-            for arg in "${array[@]}"; do
-              commands=$(nm "$arg" | grep "U " | cut -d 'U' -f 2 | cut -d ' ' -f 2 | cut -d '@' -f1 | grep -v __*)
-              IFS=$'\n' read -r -d '' -a commands_array <<< $commands
-              for cmd in "${commands_array[@]}"; do
-                authorized=false
-                for func in "${auth[@]}"; do
-                  if [[ "$cmd" == "$func" ]]; then
-                    authorized=true
-                    break
-                  fi
-                done
-                if [[ $authorized == false ]]; then
-                  printf "::error::Unauthorized function used: %s\n" "$cmd"
-                  exit 1
+          IFS=',' read -ra array <<< $EXECUTABLES
+          IFS=',' read -ra auth <<< $AUTHORIZED
+          for arg in "${array[@]}"; do
+            commands=$(nm "$arg" | grep "U " | cut -d 'U' -f 2 | cut -d ' ' -f 2 | cut -d '@' -f1 | grep -v __*)
+            IFS=$'\n' read -r -d '' -a commands_array <<< $commands
+            for cmd in "${commands_array[@]}"; do
+              authorized=false
+              for func in "${auth[@]}"; do
+                if [[ "$cmd" == "$func" ]]; then
+                  authorized=true
+                  break
                 fi
               done
+              if [[ $authorized == false ]]; then
+                printf "::error::Unauthorized function used: %s\n" "$cmd"
+                exit 1
+              fi
             done
-            exit 0
+          done
+          exit 0
 
   check_coding_style:
     needs: check_banned_functions
