[EDIT] Error display

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -34,7 +34,7 @@ jobs:
           temp=$(echo $MIRROR_URL | cut -d ':' -f 2 | sed "s/\.git//")
           if [ $temp = ${{ github.repository }} ]; then
             printf "::notice::The current repository is also the target repository\n"
-            exit 0
+            exit 1
           fi
 
 
@@ -58,7 +58,7 @@ jobs:
             NAME=$(echo $temp | cut -d '/' -f 2)
             LINE=$(echo $line | cut -d ':' -f 2)
             NBR=$(echo $line | cut -d ':' -f 4)
-            ERROR=$(printf "%s coding style error: %s#L%s" "$TYPE" "$NAME" "$LINE")
+            ERROR=$(printf "%s coding style error:" "$TYPE")
             echo "::error file=$NAME,line=$LINE,title=$ERROR::$NBR"
           done
           if [ -s coding-style-reports.log ]; then
