[EDIT] chocolatine to add new features

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -17,8 +17,8 @@ on:
 
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-NAN-2-1-chocolatine-matisse.marsac.git"
-  EXECUTABLES: "hashtable.a"
-  # BANNED_FUNC: "puts,exit,strdup,strndup,strcmp,strncmp,strcat,strncat,strlen,atoi,realloc,calloc"
+  EXECUTABLES: "hashtable.a,secured"
+  AUTHORIZED: "write,malloc,free"
 
 jobs:
   check_coding_style:
@@ -74,6 +74,27 @@ jobs:
               printf "::error::%s does not exist or is not executable" "$arg"
               exit 1
             fi
+          done
+          exit 0
+
+  check_banned_functions:
+    needs: check_program_compilation
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout@v4
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: check-banned
+        run: IFS=',' read -ra array <<< "$EXECUTABLES"
+          for arg in "${array[@]}"; do
+            commands=nm "$arg" | grep "U " | cut -d 'U' -f 2 | cut -d '@' -f1
+            for cmd in "${commands}"; do
+              if [ "$cmd" = "$2arg" ]; then
+                printf "::error::Invalid use of %s" "$CMD"
+                exit 1
+              fi
+            done
           done
           exit 0
 
