[EDIT] Mirroring condition

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -77,33 +77,34 @@ jobs:
           done
           exit 0
 
-  check_banned_functions:
-    needs: check_program_compilation
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout@v4
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: run-compilation
-        run: make
-        timeout-minutes: 2
-      - name: check-banned
-        run: |
-          IFS=',' read -ra array <<< "$EXECUTABLES"
-          for arg in "${array[@]}"; do
-            commands=nm "$arg" | grep "U " | cut -d 'U' -f 2 | cut -d '@' -f1
-            for cmd in "${commands}"; do
-              for func in "$AUTHORIZED"; do
-                printf "%s -- %s\n" "$cmd" "$func"
-                if [ "$cmd" != "$func" ]; then
-                  printf "::error::Invalid use of %s" "$cmd"
-                  exit 1
-                fi
-              done
-            done
-          done
-          exit 0
+  # check_banned_functions:
+  #   needs: check_program_compilation
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: checkout@v4
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #     - name: run-compilation
+  #       run: make
+  #       timeout-minutes: 2
+  #     - name: check-banned
+  #       run: |
+  #         IFS=',' read -ra array <<< "$EXECUTABLES"
+  #         for arg in "${array[@]}"; do
+  #           commands=nm "$arg" | grep "U " | cut -d 'U' -f 2 | cut -d '@' -f1
+  #           IFS='\n' read -ra array <<< "$EXECUTABLES"
+  #           for cmd in "${commands}"; do
+  #             for func in "$AUTHORIZED"; do
+  #               printf "%s -- %s\n" "$cmd" "$func"
+  #               if [ "$cmd" != "$func" ]; then
+  #                 printf "::error::Invalid use of %s" "$cmd"
+  #                 exit 1
+  #               fi
+  #             done
+  #           done
+  #         done
+  #         exit 0
 
   run_tests:
     needs: check_banned_functions
@@ -121,6 +122,7 @@ jobs:
 
   push_to_mirror:
     needs: run_tests
+    if: ${{ github.event_name == 'push' }}
     runs-on: ubuntu-latest
     steps:
       - name: checkout@v4
